version: '3'
services:
  time-eureka-server:
    image: "pedrogalan/time-eureka-server:0.0.1-SNAPSHOT"
    ports:
      - "8761:8761"

  time-config-server:
    image: "pedrogalan/time-config-server:0.0.1-SNAPSHOT"
    ports:
      - "8082:8082"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-service:
    image: "pedrogalan/time-service:0.0.1-SNAPSHOT"
    ports:
      - "8081"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-ui:
    image: "pedrogalan/time-ui:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka
        SPRING_RABBITMQ_HOST: time-rabbitmq

  time-hystrix-dashboard:
    image: "pedrogalan/time-hystrix-dashboard:0.0.1-SNAPSHOT"
    ports:
      - "8083:8083"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-intake:
    image: "pedrogalan/time-intake:0.0.1-SNAPSHOT"
    ports:
      - "8084:8084"
    environment:
        SPRING_RABBITMQ_HOST: time-rabbitmq

  time-rabbitmq:
    image: "rabbitmq:3.6.9-management"
    ports:
      - "15672:15672"
      - "5672:5672"
