version: '3'
services:
  time-eureka-server:
    image: "pedrogalan/time-eureka-server:0.0.1-SNAPSHOT"
    ports:
      - "8761:8761"

  time-config-server:
    image: "pedrogalan/time-config-server:0.0.1-SNAPSHOT"
    ports:
      - "8082:8082"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-service:
    image: "pedrogalan/time-service:0.0.1-SNAPSHOT"
    ports:
      - "8081"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-ui:
    image: "pedrogalan/time-ui:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka

  time-hystrix-dashboard:
    image: "pedrogalan/time-hystrix-dashboard:0.0.1-SNAPSHOT"
    ports:
      - "8083:8083"
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://time-eureka-server:8761/eureka
